/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module vsdbabysoc(clk, reset, en, led);
  wire [7:0] _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  wire _4_;
  wire _5_;
  wire _6_;
  input clk;
  input en;
  wire gclk;
  output [7:0] led;
  reg [7:0] led;
  input reset;
  assign _0_[1] = led[0] ^ led[1];
  assign _2_ = led[2] & _1_;
  assign _0_[2] = led[2] ^ _1_;
  assign _3_ = led[3] & _2_;
  assign _0_[3] = led[3] ^ _2_;
  assign _4_ = led[4] & _3_;
  assign _0_[4] = led[4] ^ _3_;
  assign _5_ = led[5] & _4_;
  assign _0_[5] = led[5] ^ _4_;
  assign _6_ = ~(led[6] & _5_);
  assign _0_[6] = led[6] ^ _5_;
  assign _0_[7] = ~(led[7] ^ _6_);
  always @(posedge gclk or posedge reset)
    if (reset)
      led[0] <= 0;
    else
      led[0] <= _0_[0];
  always @(posedge gclk or posedge reset)
    if (reset)
      led[1] <= 0;
    else
      led[1] <= _0_[1];
  always @(posedge gclk or posedge reset)
    if (reset)
      led[2] <= 0;
    else
      led[2] <= _0_[2];
  always @(posedge gclk or posedge reset)
    if (reset)
      led[3] <= 0;
    else
      led[3] <= _0_[3];
  always @(posedge gclk or posedge reset)
    if (reset)
      led[4] <= 0;
    else
      led[4] <= _0_[4];
  always @(posedge gclk or posedge reset)
    if (reset)
      led[5] <= 0;
    else
      led[5] <= _0_[5];
  always @(posedge gclk or posedge reset)
    if (reset)
      led[6] <= 0;
    else
      led[6] <= _0_[6];
  always @(posedge gclk or posedge reset)
    if (reset)
      led[7] <= 0;
    else
      led[7] <= _0_[7];
  assign gclk = en & clk;
  assign _0_[0] = ~led[0];
  assign _1_ = led[0] & led[1];
endmodule
