/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/clk_gate.v:1" *)
module clk_gate(clk, en, gclk);
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/clk_gate.v:2" *)
  input clk;
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/clk_gate.v:3" *)
  input en;
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/clk_gate.v:4" *)
  output gclk;
  assign gclk = en & clk;
endmodule

(* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/rvmyth.v:1" *)
module rvmyth(clk, reset, led);
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/rvmyth.v:6" *)
  wire [7:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/rvmyth.v:2" *)
  input clk;
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/rvmyth.v:4" *)
  output [7:0] led;
  reg [7:0] led;
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/rvmyth.v:3" *)
  input reset;
  assign _00_[1] = led[0] ^ led[1];
  assign _01_ = ~(led[0] & led[1]);
  assign _00_[2] = ~(_01_ ^ led[2]);
  assign _02_ = led[2] & ~(_01_);
  assign _00_[3] = _02_ ^ led[3];
  assign _03_ = ~(led[2] & led[3]);
  assign _04_ = _03_ | _01_;
  assign _00_[4] = ~(_04_ ^ led[4]);
  assign _05_ = led[4] & ~(_04_);
  assign _00_[5] = _05_ ^ led[5];
  assign _06_ = ~(led[4] & led[5]);
  assign _07_ = _06_ | _04_;
  assign _00_[6] = ~(_07_ ^ led[6]);
  assign _08_ = led[6] & ~(_07_);
  assign _00_[7] = _08_ ^ led[7];
  assign _00_[0] = ~led[0];
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/rvmyth.v:6" *)
  always @(posedge clk or posedge reset)
    if (reset)
      led[0] <= 0;
    else
      led[0] <= _00_[0];
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/rvmyth.v:6" *)
  always @(posedge clk or posedge reset)
    if (reset)
      led[1] <= 0;
    else
      led[1] <= _00_[1];
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/rvmyth.v:6" *)
  always @(posedge clk or posedge reset)
    if (reset)
      led[2] <= 0;
    else
      led[2] <= _00_[2];
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/rvmyth.v:6" *)
  always @(posedge clk or posedge reset)
    if (reset)
      led[3] <= 0;
    else
      led[3] <= _00_[3];
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/rvmyth.v:6" *)
  always @(posedge clk or posedge reset)
    if (reset)
      led[4] <= 0;
    else
      led[4] <= _00_[4];
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/rvmyth.v:6" *)
  always @(posedge clk or posedge reset)
    if (reset)
      led[5] <= 0;
    else
      led[5] <= _00_[5];
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/rvmyth.v:6" *)
  always @(posedge clk or posedge reset)
    if (reset)
      led[6] <= 0;
    else
      led[6] <= _00_[6];
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/rvmyth.v:6" *)
  always @(posedge clk or posedge reset)
    if (reset)
      led[7] <= 0;
    else
      led[7] <= _00_[7];
endmodule

(* top =  1  *)
(* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/vsdbabysoc.v:1" *)
module vsdbabysoc(clk, reset, en, led);
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/vsdbabysoc.v:2" *)
  input clk;
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/vsdbabysoc.v:4" *)
  input en;
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/vsdbabysoc.v:8" *)
  wire gclk;
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/vsdbabysoc.v:5" *)
  output [7:0] led;
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/vsdbabysoc.v:3" *)
  input reset;
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/vsdbabysoc.v:11" *)
  clk_gate u_clk_gate (
    .clk(clk),
    .en(en),
    .gclk(gclk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/vboxuser/VSDBabySoCC/VSDBabySoC/src/module/vsdbabysoc.v:18" *)
  rvmyth u_rvmyth (
    .clk(gclk),
    .led(led),
    .reset(reset)
  );
endmodule
